name: Android Pull Request & Master CI & CD to Firebase

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup JDK
        uses: actions/setup-java@v2.5.0
        with:
         distribution: 'temurin'
         java-version: '11'
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
