name: Android Pull Request & Master CI & CD to Firebase

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup JDK
        uses: actions/setup-java@v2.5.0
        with:
         distribution: 'temurin'
         java-version: '11'
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  build:
    name: Upload APK to App Tester
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Setup JDK
      uses: actions/setup-java@v2.5.0
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: build release 
      run: bash ./gradlew assembleDebug
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
      with:
        appId: '1:783147595086:android:12df0be2f0917d30041a1f'
        token: '1//0gMhKE9eX516XCgYIARAAGBASNwF-L9IrMkKn4kwv_xReaikQYJHWO5smvmcIts8LDgF700LkDxQK6z187BIzIC66mAG0DAzy_sE'
        groups: BlogExplorer-Tester
        file: app/build/outputs/apk/debug/app-debug.apk

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set execution flag for gradlew
        run: chmod +x gradlew    
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
